# Javascript: Eze Coe Compile
# https://docs.microsoft.com/en-gb/azure/devops/pipelines/ecosystems/javascript
#
# Pipeline Link:
# see https://dev.azure.com/riversafe/DevSecOps/_build/results?buildId=461


trigger:
  - main
  - develop

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    node_14_x:
      node_version: 14.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: 'Use Node 14'

- script: |
    npm install
    npm run test:ci
  displayName: 'Tests'

# https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'reports/*-junit.xml'
    failTaskOnFailedTests: true

#  https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/test/publish-code-coverage-results
#  WARNING: ado help page for version 1 which is not installed https://dev.azure.com/riversafe/DevSecOps/
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'frontend/reports/coverage/cobertura-coverage.xml'
    pathToSources: 'frontend/src'
  displayName: 'Frontend Coverage Results'

# https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
- script: |
    docker pull riversafe/eze-cli:latest --quiet
    chmod o+rw .
    docker run --rm -e "EZE_APIKEY=$EZE_APIKEY" -e "BUILD_SOURCEBRANCHNAME=$BUILD_SOURCEBRANCHNAME" -e "BUILD_REPOSITORY_URI=$BUILD_REPOSITORY_URI" -e "SYSTEM_PULLREQUEST_SOURCEBRANCH=$SYSTEM_PULLREQUEST_SOURCEBRANCH" -v "$(pwd)":/data riversafe/eze-cli test -s ci
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Console'